Simulation = "concordia"
Servers = 1
Bf = 19
Rounds = 10
Suite = "bn256.G2"
Seed = 123456789
Threshold = 5
CommunicationMode = 1
Gossiptime = 100
GossipPeers = 5
BlockSize = 1000000
MaxRoundLoops = 4
ShardNum = 1

Hosts
20
